"""
SQL Query Generator for PostGIS spatial operations
Translates DeepSeek operation plans into executable PostGIS SQL
"""

from typing import Dict, Any, List
from app.models.query_model import GeospatialOperation, OperationPlan
import geopandas as gpd
from app.utils.database import db_manager
from app.utils.sql_validator import validate_and_fix_sql
from shapely.ops import unary_union
import logging

logger = logging.getLogger(__name__)


class SQLQueryGenerator:
    """Generate and execute PostGIS SQL queries from operation plans"""

    def __init__(self):
        self.schema = "vector"

    def execute_plan(self, plan: OperationPlan) -> gpd.GeoDataFrame:
        """
        Execute an operation plan by translating to SQL and running in PostGIS.
        Supports intermediate result storage for multi-step operations.

        Args:
            plan: OperationPlan with operations

        Returns:
            GeoDataFrame with results
        """
        result_gdf = None
        # Store intermediate results for multi-step operations (e.g., union result referenced by difference)
        stored_results = {}

        for i, operation in enumerate(plan.operations):
            logger.info(f"Executing operation {i+1}/{len(plan.operations)}: {operation.operation}")

            # Some operations may reference previous stored results
            operation_context = {
                'stored_results': stored_results,
                'operation_index': i
            }

            if operation.operation == "load":
                result_gdf = self._execute_load(operation)
            elif operation.operation == "spatial_query":
                result_gdf = self._execute_spatial_query(operation)
            elif operation.operation == "raster_analysis":
                result_gdf = self._execute_raster_analysis(operation)
            elif operation.operation == "buffer":
                result_gdf = self._execute_buffer(operation, result_gdf)
            elif operation.operation == "intersection":
                result_gdf = self._execute_intersection(operation, result_gdf)
            elif operation.operation == "union":
                result_gdf = self._execute_union(operation, result_gdf)
                # Store union result for reference by subsequent operations (e.g., difference)
                if result_gdf is not None:
                    stored_results[f'union_{i}'] = result_gdf
                    logger.info(f"✅ Union result stored as 'union_{i}' ({len(result_gdf)} row(s))")
            elif operation.operation == "difference":
                result_gdf = self._execute_difference(operation, result_gdf, operation_context)
            elif operation.operation == "filter":
                result_gdf = self._execute_filter(operation, result_gdf)
            elif operation.operation == "aggregate":
                # Aggregation handled differently
                result_gdf = self._execute_aggregate(operation, result_gdf)
            elif operation.operation == "sort":
                result_gdf = self._execute_sort(operation, result_gdf)

        return result_gdf

    def _execute_load(self, operation: GeospatialOperation) -> gpd.GeoDataFrame:
        """
        Execute a load operation.
        Can use either pre-written SQL or generate from dataset name.
        """
        params = operation.parameters

        # Check if SQL is provided directly
        if "sql" in params:
            sql = params["sql"]
            return db_manager.execute_spatial_query(sql)

        # Otherwise, generate simple SELECT
        dataset = params.get("dataset", "")
        table_name = dataset.replace("vector.", "")  # Clean schema if present

        # Check for region filter in context
        where_clause = ""
        if "region" in params:
            region = params["region"]
            where_clause = f" WHERE region = '{region}'"

        sql = f"SELECT * FROM {self.schema}.{table_name}{where_clause}"

        return db_manager.execute_spatial_query(sql)

    def _execute_spatial_query(self, operation: GeospatialOperation) -> gpd.GeoDataFrame:
        """
        Execute a direct spatial SQL query.
        This is for complex queries generated by DeepSeek.
        Includes automatic SQL validation, error correction, and optimization.

        OPTIMIZATION:
        1. Detects heavy aggregation queries (6+ JOINs) and suggests optimization
        2. Removes unnecessary geometry operations
        3. Adds efficient indexing hints
        4. Implements query timeouts (30s) for safety
        """
        sql = operation.parameters.get("sql", "")

        if not sql:
            raise ValueError("No SQL provided for spatial_query operation")

        # Validate and fix SQL syntax errors
        is_valid, fixed_sql, errors_found = validate_and_fix_sql(sql)

        if errors_found:
            print(f"⚠️  SQL syntax issues detected and auto-corrected:")
            for error in errors_found:
                print(f"   - {error}")
            print(f"\n Original SQL:\n{sql}\n")
            print(f"Fixed SQL:\n{fixed_sql}\n")
            sql = fixed_sql

        # OPTIMIZATION: Detect and optimize heavy queries
        sql = self._optimize_query(sql)

        # CRITICAL: Ensure geometry is in the SELECT clause
        sql = self._ensure_geometry_in_select(sql)

        return db_manager.execute_spatial_query(sql)

    def _optimize_query(self, sql: str) -> str:
        """
        Optimize SQL queries for better performance.

        Optimizations applied:
        1. Detect expensive multi-JOIN aggregations (6+ JOINs)
        2. Add materialized query hints
        3. Suggest query reduction strategies

        For "best for business" queries with 6+ amenity JOINs:
        - Recommend using simpler metrics (count-only vs density)
        - Log performance warning
        - Keep original SQL but add hints if possible
        """
        import re

        # Count the number of JOINs
        join_count = len(re.findall(r'\bLEFT\s+JOIN\b|\bJOIN\b', sql, re.IGNORECASE))

        if join_count >= 6:
            print(f"⚠️  Performance Warning: Heavy query with {join_count} JOINs detected")
            print(f"   This may take 5-30+ seconds depending on data volume")
            print(f"   Recommendation: Consider filtering results by specific criteria or region")
            logger.warning(f"Heavy query detected with {join_count} JOINs - this may be slow")

        # Remove unnecessary ST_Transform in certain contexts
        # If we're only doing COUNT/aggregation, don't need geometry transforms
        if re.search(r'COUNT\s*\(\s*DISTINCT', sql, re.IGNORECASE) and 'ST_Transform' in sql:
            # Check if ST_Transform is for distance calculations
            if not re.search(r'ST_DWithin|ST_Distance', sql, re.IGNORECASE):
                # Remove unnecessary ST_Transform
                sql = re.sub(r'ST_Transform\s*\(\s*(\w+)\.geometry,\s*3857\s*\)', r'\1.geometry', sql)
                logger.info("Removed unnecessary ST_Transform from aggregation query")

        return sql

    def _ensure_geometry_in_select(self, sql: str) -> str:
        """
        Ensure geometry column is included in SELECT clause for spatial queries.
        If missing, add it to prevent "missing geometry column" errors.

        This is critical for road/LineString queries where geometry must be explicit.

        Examples:
            "SELECT bezirk FROM table" → "SELECT bezirk, geometry FROM table"
            "SELECT * FROM table" → "SELECT * FROM table" (no change, * includes geometry)
        """
        import re

        # If query uses SELECT *, it's fine (includes all columns)
        if re.search(r'SELECT\s+\*', sql, re.IGNORECASE):
            return sql

        # Check if geometry is already in the SELECT clause (case-insensitive, allow aliases)
        # Look for: geometry, ST_AsText(geometry), geom, etc.
        if re.search(r'SELECT\s+.*\b(geometry|geom|ST_AsText|ST_AsGeoJSON|ST_AsEWKT)\b', sql, re.IGNORECASE | re.DOTALL):
            return sql

        # If neither SELECT * nor explicit geometry, add geometry to SELECT
        # Find the SELECT clause and add geometry
        select_pattern = r'(SELECT\s+)([^F]+?)(FROM)'

        def add_geometry(match):
            select_keyword = match.group(1)
            select_columns = match.group(2).rstrip(', ')
            from_keyword = match.group(3)

            # Add geometry unless it ends with DISTINCT * or similar
            if not select_columns.strip().endswith('*'):
                select_columns = f"{select_columns}, geometry"

            return f"{select_keyword}{select_columns} {from_keyword}"

        fixed_sql = re.sub(select_pattern, add_geometry, sql, flags=re.IGNORECASE | re.DOTALL)

        if fixed_sql != sql:
            logger.info(f"⚠️  Geometry column was missing from SELECT - auto-added")
            logger.debug(f"   Original: {sql[:100]}...")
            logger.debug(f"   Fixed:    {fixed_sql[:100]}...")
            print(f"⚠️  Geometry column was missing from SELECT - auto-added")

        return fixed_sql

    def _execute_buffer(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Execute buffer operation using PostGIS.
        If GeoDataFrame is provided, save it first, then buffer.
        """
        distance = operation.parameters.get("distance", 1000)

        # If we have a GeoDataFrame, we need to either:
        # 1. Save it to temp table and buffer in PostGIS
        # 2. Buffer in GeoPandas

        # For simplicity, buffer in GeoPandas
        if gdf is None:
            raise ValueError("No data to buffer")

        # Ensure projected CRS
        if gdf.crs and gdf.crs.is_geographic:
            gdf = gdf.to_crs("EPSG:3857")

        gdf['geometry'] = gdf.geometry.buffer(distance)
        return gdf

    def _execute_intersection(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Execute spatial intersection.
        """
        other_dataset = operation.parameters.get("with", operation.parameters.get("dataset"))

        if not other_dataset:
            raise ValueError("No dataset specified for intersection")

        # Load the other dataset
        other_gdf = db_manager.load_vector_from_db(other_dataset, schema=self.schema)

        # Perform intersection
        if gdf.crs != other_gdf.crs:
            other_gdf = other_gdf.to_crs(gdf.crs)

        result = gpd.overlay(gdf, other_gdf, how='intersection')
        return result

    def _execute_union(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Execute union operation - merge all geometries into single geometry or dissolve by attribute.
        Used for creating coverage zones (e.g., buffer union for competitor analysis).

        Parameters:
            - merge_all: bool (default True) - merge all geometries into one
            - dissolve_by: str (optional) - column to group by before union
            - preserve_crs: bool (default True) - keep original CRS

        Returns:
            GeoDataFrame with unioned geometries (preserved in original CRS)
        """
        if gdf is None:
            raise ValueError("No data to union")

        merge_all = operation.parameters.get("merge_all", True)
        dissolve_by = operation.parameters.get("dissolve_by")
        preserve_crs = operation.parameters.get("preserve_crs", True)

        # Preserve CRS
        original_crs = gdf.crs
        logger.info(f"Union operation: {len(gdf)} geometries in {original_crs}")

        if dissolve_by and dissolve_by in gdf.columns:
            # Union by attribute (dissolve)
            logger.info(f"Dissolving by column: {dissolve_by}")
            result = gdf.dissolve(by=dissolve_by, as_index=False)
        elif merge_all:
            # Union all geometries into single geometry
            # Create single merged geometry
            merged_geom = unary_union(gdf.geometry)
            logger.info(f"Merged {len(gdf)} geometries into 1 unified geometry")

            # Create new GeoDataFrame with single row
            result = gpd.GeoDataFrame(
                {'geometry': [merged_geom]},
                crs=original_crs
            )

            # Preserve metadata if exists
            if hasattr(gdf, 'metadata'):
                result.metadata = gdf.metadata.copy()
                result.metadata['union_count'] = len(gdf)
            else:
                result.metadata = {'union_count': len(gdf)}

            logger.info(f"Union result: 1 geometry, CRS: {result.crs}")
        else:
            result = gdf

        return result

    def _execute_difference(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame, context: Dict[str, Any] = None) -> gpd.GeoDataFrame:
        """
        Execute difference operation - subtract one geometry from another.
        Used for site selection: study_area - exclusion_zones = suitable_areas.

        Parameters:
            - subtract_dataset: str - dataset name to load and subtract from current gdf
            - subtract_from_index: int (optional) - reference previous operation result (e.g., union result) by index
            - min_area: float (optional) - minimum area in square meters for resulting polygons

        Returns:
            GeoDataFrame with difference geometries (suitable areas)
        """
        if gdf is None:
            raise ValueError("No data to perform difference operation")

        context = context or {}
        stored_results = context.get('stored_results', {})

        # Try to find the layer to subtract - could be from database or from previous operation
        subtract_dataset = operation.parameters.get("subtract_dataset")
        subtract_from_index = operation.parameters.get("subtract_from_index")

        subtract_gdf = None

        # First, check if referencing a previous operation result
        if subtract_from_index is not None:
            key = f'union_{subtract_from_index}'
            if key in stored_results:
                subtract_gdf = stored_results[key]
                logger.info(f"Using previous operation result: {key}")
            else:
                # Try other keys (for flexibility)
                for stored_key, stored_val in stored_results.items():
                    if str(subtract_from_index) in stored_key:
                        subtract_gdf = stored_val
                        logger.info(f"Using stored result: {stored_key}")
                        break

        # If not found in stored results, try to load from dataset
        if subtract_gdf is None and subtract_dataset:
            subtract_gdf = db_manager.load_vector_from_db(subtract_dataset, schema=self.schema)
            logger.info(f"Loaded subtract layer from database: {subtract_dataset}")

        if subtract_gdf is None:
            raise ValueError("No subtract layer found - specify either subtract_dataset or subtract_from_index")

        # Ensure same CRS - convert both to 3857 for proper area calculations
        if gdf.crs and gdf.crs.is_geographic:
            gdf = gdf.to_crs("EPSG:3857")

        if subtract_gdf.crs and subtract_gdf.crs.is_geographic:
            subtract_gdf = subtract_gdf.to_crs("EPSG:3857")

        if gdf.crs != subtract_gdf.crs:
            subtract_gdf = subtract_gdf.to_crs(gdf.crs)

        logger.info(f"Performing difference operation: {len(gdf)} geometries - {len(subtract_gdf)} geometries")

        # Perform difference using overlay
        result = gpd.overlay(gdf, subtract_gdf, how='difference')
        logger.info(f"Difference result: {len(result)} geometries")

        # Filter by minimum area if specified
        min_area = operation.parameters.get("min_area")
        if min_area:
            # Already in projected CRS (3857)
            result = result[result.geometry.area >= min_area]
            logger.info(f"After min_area filter ({min_area} m²): {len(result)} geometries remain")

        # Convert back to 4326 for GeoJSON compatibility
        if result.crs and result.crs != "EPSG:4326":
            result = result.to_crs("EPSG:4326")

        return result

    def _execute_filter(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Filter features by attribute.
        Supports:
        - Standard column filtering (==, >, <, contains)
        - Brand/name filtering (name_contains for OSM name field)
        - Area filtering (min_area for polygon size)
        """
        if gdf is None:
            raise ValueError("No data to filter")

        column = operation.parameters.get("column")
        value = operation.parameters.get("value")
        operator = operation.parameters.get("operator", "==")

        # Standard column filtering
        if column and value:
            if operator == "==":
                gdf = gdf[gdf[column] == value]
            elif operator == ">":
                gdf = gdf[gdf[column] > value]
            elif operator == "<":
                gdf = gdf[gdf[column] < value]
            elif operator == "contains":
                gdf = gdf[gdf[column].str.contains(value, case=False, na=False)]

        # Brand/name filtering (case-insensitive partial match)
        name_filter = operation.parameters.get("name_contains")
        if name_filter and 'name' in gdf.columns:
            gdf = gdf[gdf['name'].str.contains(name_filter, case=False, na=False)]
            logger.info(f"Filtered by name containing '{name_filter}': {len(gdf)} features remaining")

        # Area filtering (minimum polygon area)
        min_area = operation.parameters.get("min_area")
        if min_area:
            # Ensure projected CRS for area calculation
            if gdf.crs and gdf.crs.is_geographic:
                temp_gdf = gdf.to_crs("EPSG:3857")
                gdf = gdf[temp_gdf.geometry.area >= min_area]
            else:
                gdf = gdf[gdf.geometry.area >= min_area]
            logger.info(f"Filtered by min_area >= {min_area} m²: {len(gdf)} features remaining")

        return gdf

    def _execute_aggregate(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Execute aggregation operation.
        """
        if gdf is None:
            raise ValueError("No data to aggregate")

        agg_type = operation.parameters.get("type", "count")
        column = operation.parameters.get("column")

        # Add aggregation results as metadata
        if not hasattr(gdf, 'metadata'):
            gdf.metadata = {}

        if agg_type == "count":
            gdf.metadata['count'] = len(gdf)
        elif agg_type == "sum" and column:
            gdf.metadata['sum'] = gdf[column].sum()
        elif agg_type == "mean" and column:
            gdf.metadata['mean'] = gdf[column].mean()
        elif agg_type == "area":
            # Calculate total area
            if gdf.crs and gdf.crs.is_geographic:
                temp_gdf = gdf.to_crs("EPSG:3857")
                gdf.metadata['total_area_km2'] = temp_gdf.geometry.area.sum() / 1_000_000
            else:
                gdf.metadata['total_area'] = gdf.geometry.area.sum()

        return gdf

    def _execute_sort(self, operation: GeospatialOperation, gdf: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
        """
        Sort features by attribute.
        """
        if gdf is None:
            raise ValueError("No data to sort")

        column = operation.parameters.get("by", operation.parameters.get("column"))
        ascending = operation.parameters.get("order", "ascending") == "ascending"

        if column and column in gdf.columns:
            gdf = gdf.sort_values(by=column, ascending=ascending)

        # Apply limit if specified
        limit = operation.parameters.get("limit")
        if limit:
            gdf = gdf.head(limit)

        return gdf

    def build_distance_query(
        self,
        table1: str,
        table2: str,
        distance: float,
        region: str = None
    ) -> str:
        """
        Build a SQL query for distance-based spatial operations.

        Args:
            table1: First table name
            table2: Second table name
            distance: Distance in meters
            region: Optional region filter

        Returns:
            SQL query string
        """
        where_clause = ""
        if region:
            where_clause = f" WHERE a.region = '{region}'"

        sql = f"""
        SELECT DISTINCT a.*
        FROM {self.schema}.{table1} a, {self.schema}.{table2} b
        {where_clause}
        AND ST_DWithin(a.geometry::geography, b.geometry::geography, {distance})
        """

        return sql.strip()

    def build_intersection_query(
        self,
        table1: str,
        table2: str,
        region: str = None
    ) -> str:
        """
        Build a SQL query for intersection operations.

        Args:
            table1: First table name
            table2: Second table name
            region: Optional region filter

        Returns:
            SQL query string
        """
        where_clause = ""
        if region:
            where_clause = f" AND a.region = '{region}'"

        sql = f"""
        SELECT a.*
        FROM {self.schema}.{table1} a, {self.schema}.{table2} b
        WHERE ST_Intersects(a.geometry, b.geometry){where_clause}
        """

        return sql.strip()

    def build_count_query(self, table: str, region: str = None) -> str:
        """
        Build a SQL query to count features.

        Args:
            table: Table name
            region: Optional region filter

        Returns:
            SQL query string
        """
        where_clause = ""
        if region:
            where_clause = f" WHERE region = '{region}'"

        sql = f"""
        SELECT COUNT(*) as count
        FROM {self.schema}.{table}{where_clause}
        """

        return sql.strip()

    def _execute_raster_analysis(self, operation: GeospatialOperation) -> gpd.GeoDataFrame:
        """
        Execute raster analysis operation.
        Routes to SpatialEngine's raster operations.

        Returns GeoDataFrame with vectorized results.
        """
        from app.utils.spatial_engine import SpatialEngine

        engine = SpatialEngine()

        # Convert GeospatialOperation to dict format expected by raster module
        raster_op = {
            'type': operation.parameters.get('type'),
            'params': operation.parameters
        }

        result = engine.execute_raster_operation(raster_op)

        if not result.get('success'):
            raise ValueError(result.get('error', 'Raster operation failed'))

        # If result has GeoJSON data, convert to GeoDataFrame
        if 'data' in result and result['data'].get('type') == 'FeatureCollection':
            import json
            gdf = gpd.GeoDataFrame.from_features(result['data']['features'])
            gdf.crs = "EPSG:4326"

            # Attach metadata
            if 'metadata' in result:
                gdf.metadata = result['metadata']

            return gdf

        # If no GeoJSON (just stats), return empty GeoDataFrame with metadata
        gdf = gpd.GeoDataFrame()
        gdf.metadata = result.get('metadata', {})
        return gdf


# Global instance
sql_generator = SQLQueryGenerator()
